import time
from Pages.BasePage import BasePageClass
from Utilities.generate_logs import get_logs
log=get_logs()

class SellYourCar(BasePageClass):
    def __init__(self,driver):
        super().__init__(driver)
    def fill_details(self,City,Pincode,Year,Month,Brand,Model,Fuel,Version,Colour,Alternate_Fuel,Owner,Kilometers,selling_price):
        log.info('searching for city')
        self.input_text('city_XPATH',City)
        log.info('clicking on city')
        self.click('first_city_XPATH')
        log.info('clicking on pincode box')
        self.click('pincode_box_XPATH')
        log.info('searching for pincode')
        self.input_text('pincode_input_box_XPATH',Pincode)
        log.info('clicking on desired pincode')
        self.click('first_pincode_XPATH')
        log.info('clicking on next button')
        self.click('next_button_XPATH')
        log.info('selecting year')
        self.select_using_text('make_years_XPATH',Year)
        log.info('selecting month')
        self.select_using_text('make_months_XPATH',Month)
        log.info('selecting brand')
        self.select_using_text('make_XPATH',Brand)
        log.info('selecting model')
        self.select_using_text('model_XPATH',Model)
        log.info('selecting fuel')
        self.select_using_text('fuel_section_XPATH',Fuel)
        log.info('selecting version')
        self.select_using_text('version_XPATH',Version)
        log.info('selecting colour')
        self.select_using_text('colour_XPATH',Colour)
        log.info('selecting alternate fuel')
        self.select_using_text('alternate_fuel_XPATH',Alternate_Fuel)
        log.info('selecting owner')
        self.select_using_text('owner_XPATH',Owner)
        log.info('typing kilometers')
        self.input_text('kilometers_driven_XPATH',Kilometers)
        log.info('typing selling price')
        self.input_text('expected_selling_price_XPATH',selling_price)
        time.sleep(2)
        log.info('clicking on post ad')
        self.click('post_your_ad_XPATH')
        time.sleep(2)
